package DatabaseApp;


/**
* DatabaseApp/DatabaseImplOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Database.idl
* Friday, March 5, 2021 12:46:32 PM IST
*/

public interface DatabaseImplOperations 
{
  DatabaseApp.Record[] getStudentData ();
} // interface DatabaseImplOperations
