package DatabaseApp;

/**
* DatabaseApp/RecordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Database.idl
* Friday, March 5, 2021 12:46:32 PM IST
*/

public final class RecordHolder implements org.omg.CORBA.portable.Streamable
{
  public DatabaseApp.Record value = null;

  public RecordHolder ()
  {
  }

  public RecordHolder (DatabaseApp.Record initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DatabaseApp.RecordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DatabaseApp.RecordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DatabaseApp.RecordHelper.type ();
  }

}
