package DatabaseApp;


/**
* DatabaseApp/recordSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Database.idl
* Friday, March 5, 2021 12:46:32 PM IST
*/

public final class recordSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public DatabaseApp.Record value[] = null;

  public recordSeqHolder ()
  {
  }

  public recordSeqHolder (DatabaseApp.Record[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DatabaseApp.recordSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DatabaseApp.recordSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DatabaseApp.recordSeqHelper.type ();
  }

}
