package DatabaseApp;


/**
* DatabaseApp/recordSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Database.idl
* Friday, March 5, 2021 12:46:32 PM IST
*/

abstract public class recordSeqHelper
{
  private static String  _id = "IDL:DatabaseApp/recordSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, DatabaseApp.Record[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DatabaseApp.Record[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = DatabaseApp.RecordHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (DatabaseApp.recordSeqHelper.id (), "recordSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DatabaseApp.Record[] read (org.omg.CORBA.portable.InputStream istream)
  {
    DatabaseApp.Record value[] = null;
    int _len0 = istream.read_long ();
    value = new DatabaseApp.Record[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = DatabaseApp.RecordHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DatabaseApp.Record[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      DatabaseApp.RecordHelper.write (ostream, value[_i0]);
  }

}
