package DatabaseApp;


/**
* DatabaseApp/Record.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Database.idl
* Friday, March 5, 2021 12:46:32 PM IST
*/

public final class Record implements org.omg.CORBA.portable.IDLEntity
{
  public int roll = (int)0;
  public String name = null;

  public Record ()
  {
  } // ctor

  public Record (int _roll, String _name)
  {
    roll = _roll;
    name = _name;
  } // ctor

} // class Record
